'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como ResGen ou Visual Studio.
    'Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    'com a opção /str, ou recrie o projeto do VS.
    '''<summary>
    '''  Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frFR
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NavalBattle.frFR", GetType(frFR).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread atual para todas as
        '''  pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Quitter.
        '''</summary>
        Friend Shared ReadOnly Property _exit() As String
            Get
                Return ResourceManager.GetString("exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Retourner.
        '''</summary>
        Friend Shared ReadOnly Property _return() As String
            Get
                Return ResourceManager.GetString("return", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Sélectionner.
        '''</summary>
        Friend Shared ReadOnly Property _select() As String
            Get
                Return ResourceManager.GetString("select", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Environ.
        '''</summary>
        Friend Shared ReadOnly Property about() As String
            Get
                Return ResourceManager.GetString("about", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Attaquer.
        '''</summary>
        Friend Shared ReadOnly Property attack() As String
            Get
                Return ResourceManager.GetString("attack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Croiseur.
        '''</summary>
        Friend Shared ReadOnly Property battleship() As String
            Get
                Return ResourceManager.GetString("battleship", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Annuler.
        '''</summary>
        Friend Shared ReadOnly Property cancel() As String
            Get
                Return ResourceManager.GetString("cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Porte Avion.
        '''</summary>
        Friend Shared ReadOnly Property carrier() As String
            Get
                Return ResourceManager.GetString("carrier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Changer.
        '''</summary>
        Friend Shared ReadOnly Property change() As String
            Get
                Return ResourceManager.GetString("change", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Désélectionner.
        '''</summary>
        Friend Shared ReadOnly Property deselect() As String
            Get
                Return ResourceManager.GetString("deselect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Sous-Marin.
        '''</summary>
        Friend Shared ReadOnly Property destroyer() As String
            Get
                Return ResourceManager.GetString("destroyer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Exécuter.
        '''</summary>
        Friend Shared ReadOnly Property execute() As String
            Get
                Return ResourceManager.GetString("execute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Plein Écran.
        '''</summary>
        Friend Shared ReadOnly Property fullscreen() As String
            Get
                Return ResourceManager.GetString("fullscreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Hauteur.
        '''</summary>
        Friend Shared ReadOnly Property height() As String
            Get
                Return ResourceManager.GetString("height", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Langue.
        '''</summary>
        Friend Shared ReadOnly Property language() As String
            Get
                Return ResourceManager.GetString("language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Taille de la Carte.
        '''</summary>
        Friend Shared ReadOnly Property map_size() As String
            Get
                Return ResourceManager.GetString("map_size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Bouger.
        '''</summary>
        Friend Shared ReadOnly Property move() As String
            Get
                Return ResourceManager.GetString("move", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Bataille Navale.
        '''</summary>
        Friend Shared ReadOnly Property naval_battle() As String
            Get
                Return ResourceManager.GetString("naval_battle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Positioner Bateau.
        '''</summary>
        Friend Shared ReadOnly Property place() As String
            Get
                Return ResourceManager.GetString("place", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Jouer.
        '''</summary>
        Friend Shared ReadOnly Property play() As String
            Get
                Return ResourceManager.GetString("play", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Joueur 1.
        '''</summary>
        Friend Shared ReadOnly Property player_1() As String
            Get
                Return ResourceManager.GetString("player_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Joueur 2.
        '''</summary>
        Friend Shared ReadOnly Property player_2() As String
            Get
                Return ResourceManager.GetString("player_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Résolution.
        '''</summary>
        Friend Shared ReadOnly Property resolution() As String
            Get
                Return ResourceManager.GetString("resolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Appuyez sur  pour revenir au menu..
        '''</summary>
        Friend Shared ReadOnly Property return_menu() As String
            Get
                Return ResourceManager.GetString("return_menu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Tourner Bateau.
        '''</summary>
        Friend Shared ReadOnly Property rotate() As String
            Get
                Return ResourceManager.GetString("rotate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Appuyez sur  pour voir les cartes..
        '''</summary>
        Friend Shared ReadOnly Property see_maps() As String
            Get
                Return ResourceManager.GetString("see_maps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Sélectionner/Exécuter.
        '''</summary>
        Friend Shared ReadOnly Property select_execute() As String
            Get
                Return ResourceManager.GetString("select_execute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Paramètres.
        '''</summary>
        Friend Shared ReadOnly Property settings() As String
            Get
                Return ResourceManager.GetString("settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Torpilleur.
        '''</summary>
        Friend Shared ReadOnly Property submarine() As String
            Get
                Return ResourceManager.GetString("submarine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Changer Carte.
        '''</summary>
        Friend Shared ReadOnly Property switch_map() As String
            Get
                Return ResourceManager.GetString("switch_map", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Volume.
        '''</summary>
        Friend Shared ReadOnly Property volume() As String
            Get
                Return ResourceManager.GetString("volume", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Largeur.
        '''</summary>
        Friend Shared ReadOnly Property width() As String
            Get
                Return ResourceManager.GetString("width", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Tu as Perdu!.
        '''</summary>
        Friend Shared ReadOnly Property you_lost() As String
            Get
                Return ResourceManager.GetString("you_lost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a Tu as Gagné!.
        '''</summary>
        Friend Shared ReadOnly Property you_won() As String
            Get
                Return ResourceManager.GetString("you_won", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
